// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package certificate_authority

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	"github.com/openziti/edge-api/rest_model"
)

// DeleteCaOKCode is the HTTP code returned for type DeleteCaOK
const DeleteCaOKCode int = 200

/*
DeleteCaOK The delete request was successful and the resource has been removed

swagger:response deleteCaOK
*/
type DeleteCaOK struct {
	/*Denotes different type of security token related information

	 */
	WWWAuthenticate []string `json:"WWW-Authenticate"`

	/*
	  In: Body
	*/
	Payload *rest_model.Empty `json:"body,omitempty"`
}

// NewDeleteCaOK creates DeleteCaOK with default headers values
func NewDeleteCaOK() *DeleteCaOK {

	return &DeleteCaOK{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the delete ca o k response
func (o *DeleteCaOK) WithWWWAuthenticate(wWWAuthenticate []string) *DeleteCaOK {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the delete ca o k response
func (o *DeleteCaOK) SetWWWAuthenticate(wWWAuthenticate []string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the delete ca o k response
func (o *DeleteCaOK) WithPayload(payload *rest_model.Empty) *DeleteCaOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete ca o k response
func (o *DeleteCaOK) SetPayload(payload *rest_model.Empty) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteCaOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	var wWWAuthenticateIR []string
	for _, wWWAuthenticateI := range o.WWWAuthenticate {
		wWWAuthenticateIS := wWWAuthenticateI
		if wWWAuthenticateIS != "" {
			wWWAuthenticateIR = append(wWWAuthenticateIR, wWWAuthenticateIS)
		}
	}
	wWWAuthenticate := swag.JoinByFormat(wWWAuthenticateIR, "")
	if len(wWWAuthenticate) > 0 {
		hv := wWWAuthenticate[0]
		if hv != "" {
			rw.Header().Set("WWW-Authenticate", hv)
		}
	}

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteCaBadRequestCode is the HTTP code returned for type DeleteCaBadRequest
const DeleteCaBadRequestCode int = 400

/*
DeleteCaBadRequest The supplied request contains invalid fields or could not be parsed (json and non-json bodies). The error's code, message, and cause fields can be inspected for further information

swagger:response deleteCaBadRequest
*/
type DeleteCaBadRequest struct {
	/*Denotes different type of security token related information

	 */
	WWWAuthenticate []string `json:"WWW-Authenticate"`

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewDeleteCaBadRequest creates DeleteCaBadRequest with default headers values
func NewDeleteCaBadRequest() *DeleteCaBadRequest {

	return &DeleteCaBadRequest{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the delete ca bad request response
func (o *DeleteCaBadRequest) WithWWWAuthenticate(wWWAuthenticate []string) *DeleteCaBadRequest {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the delete ca bad request response
func (o *DeleteCaBadRequest) SetWWWAuthenticate(wWWAuthenticate []string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the delete ca bad request response
func (o *DeleteCaBadRequest) WithPayload(payload *rest_model.APIErrorEnvelope) *DeleteCaBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete ca bad request response
func (o *DeleteCaBadRequest) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteCaBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	var wWWAuthenticateIR []string
	for _, wWWAuthenticateI := range o.WWWAuthenticate {
		wWWAuthenticateIS := wWWAuthenticateI
		if wWWAuthenticateIS != "" {
			wWWAuthenticateIR = append(wWWAuthenticateIR, wWWAuthenticateIS)
		}
	}
	wWWAuthenticate := swag.JoinByFormat(wWWAuthenticateIR, "")
	if len(wWWAuthenticate) > 0 {
		hv := wWWAuthenticate[0]
		if hv != "" {
			rw.Header().Set("WWW-Authenticate", hv)
		}
	}

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteCaUnauthorizedCode is the HTTP code returned for type DeleteCaUnauthorized
const DeleteCaUnauthorizedCode int = 401

/*
DeleteCaUnauthorized The supplied session does not have the correct access rights to request this resource

swagger:response deleteCaUnauthorized
*/
type DeleteCaUnauthorized struct {
	/*Denotes different type of security token related information

	 */
	WWWAuthenticate []string `json:"WWW-Authenticate"`

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewDeleteCaUnauthorized creates DeleteCaUnauthorized with default headers values
func NewDeleteCaUnauthorized() *DeleteCaUnauthorized {

	return &DeleteCaUnauthorized{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the delete ca unauthorized response
func (o *DeleteCaUnauthorized) WithWWWAuthenticate(wWWAuthenticate []string) *DeleteCaUnauthorized {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the delete ca unauthorized response
func (o *DeleteCaUnauthorized) SetWWWAuthenticate(wWWAuthenticate []string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the delete ca unauthorized response
func (o *DeleteCaUnauthorized) WithPayload(payload *rest_model.APIErrorEnvelope) *DeleteCaUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete ca unauthorized response
func (o *DeleteCaUnauthorized) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteCaUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	var wWWAuthenticateIR []string
	for _, wWWAuthenticateI := range o.WWWAuthenticate {
		wWWAuthenticateIS := wWWAuthenticateI
		if wWWAuthenticateIS != "" {
			wWWAuthenticateIR = append(wWWAuthenticateIR, wWWAuthenticateIS)
		}
	}
	wWWAuthenticate := swag.JoinByFormat(wWWAuthenticateIR, "")
	if len(wWWAuthenticate) > 0 {
		hv := wWWAuthenticate[0]
		if hv != "" {
			rw.Header().Set("WWW-Authenticate", hv)
		}
	}

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteCaNotFoundCode is the HTTP code returned for type DeleteCaNotFound
const DeleteCaNotFoundCode int = 404

/*
DeleteCaNotFound The requested resource does not exist

swagger:response deleteCaNotFound
*/
type DeleteCaNotFound struct {
	/*Denotes different type of security token related information

	 */
	WWWAuthenticate []string `json:"WWW-Authenticate"`

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewDeleteCaNotFound creates DeleteCaNotFound with default headers values
func NewDeleteCaNotFound() *DeleteCaNotFound {

	return &DeleteCaNotFound{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the delete ca not found response
func (o *DeleteCaNotFound) WithWWWAuthenticate(wWWAuthenticate []string) *DeleteCaNotFound {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the delete ca not found response
func (o *DeleteCaNotFound) SetWWWAuthenticate(wWWAuthenticate []string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the delete ca not found response
func (o *DeleteCaNotFound) WithPayload(payload *rest_model.APIErrorEnvelope) *DeleteCaNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete ca not found response
func (o *DeleteCaNotFound) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteCaNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	var wWWAuthenticateIR []string
	for _, wWWAuthenticateI := range o.WWWAuthenticate {
		wWWAuthenticateIS := wWWAuthenticateI
		if wWWAuthenticateIS != "" {
			wWWAuthenticateIR = append(wWWAuthenticateIR, wWWAuthenticateIS)
		}
	}
	wWWAuthenticate := swag.JoinByFormat(wWWAuthenticateIR, "")
	if len(wWWAuthenticate) > 0 {
		hv := wWWAuthenticate[0]
		if hv != "" {
			rw.Header().Set("WWW-Authenticate", hv)
		}
	}

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteCaTooManyRequestsCode is the HTTP code returned for type DeleteCaTooManyRequests
const DeleteCaTooManyRequestsCode int = 429

/*
DeleteCaTooManyRequests The resource requested is rate limited and the rate limit has been exceeded

swagger:response deleteCaTooManyRequests
*/
type DeleteCaTooManyRequests struct {
	/*Denotes different type of security token related information

	 */
	WWWAuthenticate []string `json:"WWW-Authenticate"`

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewDeleteCaTooManyRequests creates DeleteCaTooManyRequests with default headers values
func NewDeleteCaTooManyRequests() *DeleteCaTooManyRequests {

	return &DeleteCaTooManyRequests{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the delete ca too many requests response
func (o *DeleteCaTooManyRequests) WithWWWAuthenticate(wWWAuthenticate []string) *DeleteCaTooManyRequests {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the delete ca too many requests response
func (o *DeleteCaTooManyRequests) SetWWWAuthenticate(wWWAuthenticate []string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the delete ca too many requests response
func (o *DeleteCaTooManyRequests) WithPayload(payload *rest_model.APIErrorEnvelope) *DeleteCaTooManyRequests {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete ca too many requests response
func (o *DeleteCaTooManyRequests) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteCaTooManyRequests) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	var wWWAuthenticateIR []string
	for _, wWWAuthenticateI := range o.WWWAuthenticate {
		wWWAuthenticateIS := wWWAuthenticateI
		if wWWAuthenticateIS != "" {
			wWWAuthenticateIR = append(wWWAuthenticateIR, wWWAuthenticateIS)
		}
	}
	wWWAuthenticate := swag.JoinByFormat(wWWAuthenticateIR, "")
	if len(wWWAuthenticate) > 0 {
		hv := wWWAuthenticate[0]
		if hv != "" {
			rw.Header().Set("WWW-Authenticate", hv)
		}
	}

	rw.WriteHeader(429)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteCaServiceUnavailableCode is the HTTP code returned for type DeleteCaServiceUnavailable
const DeleteCaServiceUnavailableCode int = 503

/*
DeleteCaServiceUnavailable The request could not be completed due to the server being busy or in a temporarily bad state

swagger:response deleteCaServiceUnavailable
*/
type DeleteCaServiceUnavailable struct {
	/*Denotes different type of security token related information

	 */
	WWWAuthenticate []string `json:"WWW-Authenticate"`

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewDeleteCaServiceUnavailable creates DeleteCaServiceUnavailable with default headers values
func NewDeleteCaServiceUnavailable() *DeleteCaServiceUnavailable {

	return &DeleteCaServiceUnavailable{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the delete ca service unavailable response
func (o *DeleteCaServiceUnavailable) WithWWWAuthenticate(wWWAuthenticate []string) *DeleteCaServiceUnavailable {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the delete ca service unavailable response
func (o *DeleteCaServiceUnavailable) SetWWWAuthenticate(wWWAuthenticate []string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the delete ca service unavailable response
func (o *DeleteCaServiceUnavailable) WithPayload(payload *rest_model.APIErrorEnvelope) *DeleteCaServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete ca service unavailable response
func (o *DeleteCaServiceUnavailable) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteCaServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	var wWWAuthenticateIR []string
	for _, wWWAuthenticateI := range o.WWWAuthenticate {
		wWWAuthenticateIS := wWWAuthenticateI
		if wWWAuthenticateIS != "" {
			wWWAuthenticateIR = append(wWWAuthenticateIR, wWWAuthenticateIS)
		}
	}
	wWWAuthenticate := swag.JoinByFormat(wWWAuthenticateIR, "")
	if len(wWWAuthenticate) > 0 {
		hv := wWWAuthenticate[0]
		if hv != "" {
			rw.Header().Set("WWW-Authenticate", hv)
		}
	}

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
