// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package o_id_c_authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/openziti/edge-api/rest_model"
)

// AuthenticateCertHandlerFunc turns a function with the right signature into a authenticate cert handler
type AuthenticateCertHandlerFunc func(AuthenticateCertParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AuthenticateCertHandlerFunc) Handle(params AuthenticateCertParams) middleware.Responder {
	return fn(params)
}

// AuthenticateCertHandler interface for that can handle valid authenticate cert params
type AuthenticateCertHandler interface {
	Handle(AuthenticateCertParams) middleware.Responder
}

// NewAuthenticateCert creates a new http.Handler for the authenticate cert operation
func NewAuthenticateCert(ctx *middleware.Context, handler AuthenticateCertHandler) *AuthenticateCert {
	return &AuthenticateCert{Context: ctx, Handler: handler}
}

/* AuthenticateCert swagger:route POST /cert OIDC Authentication authenticateCert

Authenticate with client certificate

Authenticates a user via client certificate for OIDC flow

*/
type AuthenticateCert struct {
	Context *middleware.Context
	Handler AuthenticateCertHandler
}

func (o *AuthenticateCert) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAuthenticateCertParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// AuthenticateCertOKBody authenticate cert o k body
//
// swagger:model AuthenticateCertOKBody
type AuthenticateCertOKBody struct {

	// auth queries
	AuthQueries []*rest_model.AuthQueryDetail `json:"authQueries"`
}

// Validate validates this authenticate cert o k body
func (o *AuthenticateCertOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAuthQueries(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *AuthenticateCertOKBody) validateAuthQueries(formats strfmt.Registry) error {
	if swag.IsZero(o.AuthQueries) { // not required
		return nil
	}

	for i := 0; i < len(o.AuthQueries); i++ {
		if swag.IsZero(o.AuthQueries[i]) { // not required
			continue
		}

		if o.AuthQueries[i] != nil {
			if err := o.AuthQueries[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("authenticateCertOK" + "." + "authQueries" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("authenticateCertOK" + "." + "authQueries" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this authenticate cert o k body based on the context it is used
func (o *AuthenticateCertOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateAuthQueries(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *AuthenticateCertOKBody) contextValidateAuthQueries(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.AuthQueries); i++ {

		if o.AuthQueries[i] != nil {
			if err := o.AuthQueries[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("authenticateCertOK" + "." + "authQueries" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("authenticateCertOK" + "." + "authQueries" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *AuthenticateCertOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AuthenticateCertOKBody) UnmarshalBinary(b []byte) error {
	var res AuthenticateCertOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
