// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package o_id_c_authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openziti/edge-api/rest_model"
)

// StartTotpEnrollmentCreatedCode is the HTTP code returned for type StartTotpEnrollmentCreated
const StartTotpEnrollmentCreatedCode int = 201

/*StartTotpEnrollmentCreated TOTP enrollment started successfully

swagger:response startTotpEnrollmentCreated
*/
type StartTotpEnrollmentCreated struct {

	/*
	  In: Body
	*/
	Payload *rest_model.DetailMfa `json:"body,omitempty"`
}

// NewStartTotpEnrollmentCreated creates StartTotpEnrollmentCreated with default headers values
func NewStartTotpEnrollmentCreated() *StartTotpEnrollmentCreated {

	return &StartTotpEnrollmentCreated{}
}

// WithPayload adds the payload to the start totp enrollment created response
func (o *StartTotpEnrollmentCreated) WithPayload(payload *rest_model.DetailMfa) *StartTotpEnrollmentCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the start totp enrollment created response
func (o *StartTotpEnrollmentCreated) SetPayload(payload *rest_model.DetailMfa) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StartTotpEnrollmentCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// StartTotpEnrollmentBadRequestCode is the HTTP code returned for type StartTotpEnrollmentBadRequest
const StartTotpEnrollmentBadRequestCode int = 400

/*StartTotpEnrollmentBadRequest The supplied request contains invalid fields or could not be parsed (json and non-json bodies). The error's code, message, and cause fields can be inspected for further information

swagger:response startTotpEnrollmentBadRequest
*/
type StartTotpEnrollmentBadRequest struct {

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewStartTotpEnrollmentBadRequest creates StartTotpEnrollmentBadRequest with default headers values
func NewStartTotpEnrollmentBadRequest() *StartTotpEnrollmentBadRequest {

	return &StartTotpEnrollmentBadRequest{}
}

// WithPayload adds the payload to the start totp enrollment bad request response
func (o *StartTotpEnrollmentBadRequest) WithPayload(payload *rest_model.APIErrorEnvelope) *StartTotpEnrollmentBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the start totp enrollment bad request response
func (o *StartTotpEnrollmentBadRequest) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StartTotpEnrollmentBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// StartTotpEnrollmentUnauthorizedCode is the HTTP code returned for type StartTotpEnrollmentUnauthorized
const StartTotpEnrollmentUnauthorizedCode int = 401

/*StartTotpEnrollmentUnauthorized The authentication request could not be processed as the credentials are invalid

swagger:response startTotpEnrollmentUnauthorized
*/
type StartTotpEnrollmentUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewStartTotpEnrollmentUnauthorized creates StartTotpEnrollmentUnauthorized with default headers values
func NewStartTotpEnrollmentUnauthorized() *StartTotpEnrollmentUnauthorized {

	return &StartTotpEnrollmentUnauthorized{}
}

// WithPayload adds the payload to the start totp enrollment unauthorized response
func (o *StartTotpEnrollmentUnauthorized) WithPayload(payload *rest_model.APIErrorEnvelope) *StartTotpEnrollmentUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the start totp enrollment unauthorized response
func (o *StartTotpEnrollmentUnauthorized) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StartTotpEnrollmentUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
