// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package service_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	"github.com/openziti/edge-api/rest_model"
)

// ListServicePolicyIdentitiesOKCode is the HTTP code returned for type ListServicePolicyIdentitiesOK
const ListServicePolicyIdentitiesOKCode int = 200

/*
ListServicePolicyIdentitiesOK A list of identities

swagger:response listServicePolicyIdentitiesOK
*/
type ListServicePolicyIdentitiesOK struct {
	/*Denotes different type of security token related information

	 */
	WWWAuthenticate []string `json:"WWW-Authenticate"`

	/*
	  In: Body
	*/
	Payload *rest_model.ListIdentitiesEnvelope `json:"body,omitempty"`
}

// NewListServicePolicyIdentitiesOK creates ListServicePolicyIdentitiesOK with default headers values
func NewListServicePolicyIdentitiesOK() *ListServicePolicyIdentitiesOK {

	return &ListServicePolicyIdentitiesOK{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the list service policy identities o k response
func (o *ListServicePolicyIdentitiesOK) WithWWWAuthenticate(wWWAuthenticate []string) *ListServicePolicyIdentitiesOK {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the list service policy identities o k response
func (o *ListServicePolicyIdentitiesOK) SetWWWAuthenticate(wWWAuthenticate []string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the list service policy identities o k response
func (o *ListServicePolicyIdentitiesOK) WithPayload(payload *rest_model.ListIdentitiesEnvelope) *ListServicePolicyIdentitiesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list service policy identities o k response
func (o *ListServicePolicyIdentitiesOK) SetPayload(payload *rest_model.ListIdentitiesEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListServicePolicyIdentitiesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	var wWWAuthenticateIR []string
	for _, wWWAuthenticateI := range o.WWWAuthenticate {
		wWWAuthenticateIS := wWWAuthenticateI
		if wWWAuthenticateIS != "" {
			wWWAuthenticateIR = append(wWWAuthenticateIR, wWWAuthenticateIS)
		}
	}
	wWWAuthenticate := swag.JoinByFormat(wWWAuthenticateIR, "")
	if len(wWWAuthenticate) > 0 {
		hv := wWWAuthenticate[0]
		if hv != "" {
			rw.Header().Set("WWW-Authenticate", hv)
		}
	}

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListServicePolicyIdentitiesBadRequestCode is the HTTP code returned for type ListServicePolicyIdentitiesBadRequest
const ListServicePolicyIdentitiesBadRequestCode int = 400

/*
ListServicePolicyIdentitiesBadRequest The requested resource does not exist

swagger:response listServicePolicyIdentitiesBadRequest
*/
type ListServicePolicyIdentitiesBadRequest struct {
	/*Denotes different type of security token related information

	 */
	WWWAuthenticate []string `json:"WWW-Authenticate"`

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewListServicePolicyIdentitiesBadRequest creates ListServicePolicyIdentitiesBadRequest with default headers values
func NewListServicePolicyIdentitiesBadRequest() *ListServicePolicyIdentitiesBadRequest {

	return &ListServicePolicyIdentitiesBadRequest{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the list service policy identities bad request response
func (o *ListServicePolicyIdentitiesBadRequest) WithWWWAuthenticate(wWWAuthenticate []string) *ListServicePolicyIdentitiesBadRequest {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the list service policy identities bad request response
func (o *ListServicePolicyIdentitiesBadRequest) SetWWWAuthenticate(wWWAuthenticate []string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the list service policy identities bad request response
func (o *ListServicePolicyIdentitiesBadRequest) WithPayload(payload *rest_model.APIErrorEnvelope) *ListServicePolicyIdentitiesBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list service policy identities bad request response
func (o *ListServicePolicyIdentitiesBadRequest) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListServicePolicyIdentitiesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	var wWWAuthenticateIR []string
	for _, wWWAuthenticateI := range o.WWWAuthenticate {
		wWWAuthenticateIS := wWWAuthenticateI
		if wWWAuthenticateIS != "" {
			wWWAuthenticateIR = append(wWWAuthenticateIR, wWWAuthenticateIS)
		}
	}
	wWWAuthenticate := swag.JoinByFormat(wWWAuthenticateIR, "")
	if len(wWWAuthenticate) > 0 {
		hv := wWWAuthenticate[0]
		if hv != "" {
			rw.Header().Set("WWW-Authenticate", hv)
		}
	}

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListServicePolicyIdentitiesUnauthorizedCode is the HTTP code returned for type ListServicePolicyIdentitiesUnauthorized
const ListServicePolicyIdentitiesUnauthorizedCode int = 401

/*
ListServicePolicyIdentitiesUnauthorized The supplied session does not have the correct access rights to request this resource

swagger:response listServicePolicyIdentitiesUnauthorized
*/
type ListServicePolicyIdentitiesUnauthorized struct {
	/*Denotes different type of security token related information

	 */
	WWWAuthenticate []string `json:"WWW-Authenticate"`

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewListServicePolicyIdentitiesUnauthorized creates ListServicePolicyIdentitiesUnauthorized with default headers values
func NewListServicePolicyIdentitiesUnauthorized() *ListServicePolicyIdentitiesUnauthorized {

	return &ListServicePolicyIdentitiesUnauthorized{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the list service policy identities unauthorized response
func (o *ListServicePolicyIdentitiesUnauthorized) WithWWWAuthenticate(wWWAuthenticate []string) *ListServicePolicyIdentitiesUnauthorized {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the list service policy identities unauthorized response
func (o *ListServicePolicyIdentitiesUnauthorized) SetWWWAuthenticate(wWWAuthenticate []string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the list service policy identities unauthorized response
func (o *ListServicePolicyIdentitiesUnauthorized) WithPayload(payload *rest_model.APIErrorEnvelope) *ListServicePolicyIdentitiesUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list service policy identities unauthorized response
func (o *ListServicePolicyIdentitiesUnauthorized) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListServicePolicyIdentitiesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	var wWWAuthenticateIR []string
	for _, wWWAuthenticateI := range o.WWWAuthenticate {
		wWWAuthenticateIS := wWWAuthenticateI
		if wWWAuthenticateIS != "" {
			wWWAuthenticateIR = append(wWWAuthenticateIR, wWWAuthenticateIS)
		}
	}
	wWWAuthenticate := swag.JoinByFormat(wWWAuthenticateIR, "")
	if len(wWWAuthenticate) > 0 {
		hv := wWWAuthenticate[0]
		if hv != "" {
			rw.Header().Set("WWW-Authenticate", hv)
		}
	}

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListServicePolicyIdentitiesTooManyRequestsCode is the HTTP code returned for type ListServicePolicyIdentitiesTooManyRequests
const ListServicePolicyIdentitiesTooManyRequestsCode int = 429

/*
ListServicePolicyIdentitiesTooManyRequests The resource requested is rate limited and the rate limit has been exceeded

swagger:response listServicePolicyIdentitiesTooManyRequests
*/
type ListServicePolicyIdentitiesTooManyRequests struct {
	/*Denotes different type of security token related information

	 */
	WWWAuthenticate []string `json:"WWW-Authenticate"`

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewListServicePolicyIdentitiesTooManyRequests creates ListServicePolicyIdentitiesTooManyRequests with default headers values
func NewListServicePolicyIdentitiesTooManyRequests() *ListServicePolicyIdentitiesTooManyRequests {

	return &ListServicePolicyIdentitiesTooManyRequests{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the list service policy identities too many requests response
func (o *ListServicePolicyIdentitiesTooManyRequests) WithWWWAuthenticate(wWWAuthenticate []string) *ListServicePolicyIdentitiesTooManyRequests {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the list service policy identities too many requests response
func (o *ListServicePolicyIdentitiesTooManyRequests) SetWWWAuthenticate(wWWAuthenticate []string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the list service policy identities too many requests response
func (o *ListServicePolicyIdentitiesTooManyRequests) WithPayload(payload *rest_model.APIErrorEnvelope) *ListServicePolicyIdentitiesTooManyRequests {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list service policy identities too many requests response
func (o *ListServicePolicyIdentitiesTooManyRequests) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListServicePolicyIdentitiesTooManyRequests) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	var wWWAuthenticateIR []string
	for _, wWWAuthenticateI := range o.WWWAuthenticate {
		wWWAuthenticateIS := wWWAuthenticateI
		if wWWAuthenticateIS != "" {
			wWWAuthenticateIR = append(wWWAuthenticateIR, wWWAuthenticateIS)
		}
	}
	wWWAuthenticate := swag.JoinByFormat(wWWAuthenticateIR, "")
	if len(wWWAuthenticate) > 0 {
		hv := wWWAuthenticate[0]
		if hv != "" {
			rw.Header().Set("WWW-Authenticate", hv)
		}
	}

	rw.WriteHeader(429)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListServicePolicyIdentitiesServiceUnavailableCode is the HTTP code returned for type ListServicePolicyIdentitiesServiceUnavailable
const ListServicePolicyIdentitiesServiceUnavailableCode int = 503

/*
ListServicePolicyIdentitiesServiceUnavailable The request could not be completed due to the server being busy or in a temporarily bad state

swagger:response listServicePolicyIdentitiesServiceUnavailable
*/
type ListServicePolicyIdentitiesServiceUnavailable struct {
	/*Denotes different type of security token related information

	 */
	WWWAuthenticate []string `json:"WWW-Authenticate"`

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewListServicePolicyIdentitiesServiceUnavailable creates ListServicePolicyIdentitiesServiceUnavailable with default headers values
func NewListServicePolicyIdentitiesServiceUnavailable() *ListServicePolicyIdentitiesServiceUnavailable {

	return &ListServicePolicyIdentitiesServiceUnavailable{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the list service policy identities service unavailable response
func (o *ListServicePolicyIdentitiesServiceUnavailable) WithWWWAuthenticate(wWWAuthenticate []string) *ListServicePolicyIdentitiesServiceUnavailable {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the list service policy identities service unavailable response
func (o *ListServicePolicyIdentitiesServiceUnavailable) SetWWWAuthenticate(wWWAuthenticate []string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the list service policy identities service unavailable response
func (o *ListServicePolicyIdentitiesServiceUnavailable) WithPayload(payload *rest_model.APIErrorEnvelope) *ListServicePolicyIdentitiesServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list service policy identities service unavailable response
func (o *ListServicePolicyIdentitiesServiceUnavailable) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListServicePolicyIdentitiesServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	var wWWAuthenticateIR []string
	for _, wWWAuthenticateI := range o.WWWAuthenticate {
		wWWAuthenticateIS := wWWAuthenticateI
		if wWWAuthenticateIS != "" {
			wWWAuthenticateIR = append(wWWAuthenticateIR, wWWAuthenticateIS)
		}
	}
	wWWAuthenticate := swag.JoinByFormat(wWWAuthenticateIR, "")
	if len(wWWAuthenticate) > 0 {
		hv := wWWAuthenticate[0]
		if hv != "" {
			rw.Header().Set("WWW-Authenticate", hv)
		}
	}

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
