// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package role_attributes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	"github.com/openziti/edge-api/rest_model"
)

// ListEdgeRouterRoleAttributeUsageOKCode is the HTTP code returned for type ListEdgeRouterRoleAttributeUsageOK
const ListEdgeRouterRoleAttributeUsageOKCode int = 200

/*
ListEdgeRouterRoleAttributeUsageOK A list of role attributes with per-source usage breakdowns

swagger:response listEdgeRouterRoleAttributeUsageOK
*/
type ListEdgeRouterRoleAttributeUsageOK struct {
	/*Denotes different type of security token related information

	 */
	WWWAuthenticate []string `json:"WWW-Authenticate"`

	/*
	  In: Body
	*/
	Payload *rest_model.ListRoleAttributeUsageEnvelope `json:"body,omitempty"`
}

// NewListEdgeRouterRoleAttributeUsageOK creates ListEdgeRouterRoleAttributeUsageOK with default headers values
func NewListEdgeRouterRoleAttributeUsageOK() *ListEdgeRouterRoleAttributeUsageOK {

	return &ListEdgeRouterRoleAttributeUsageOK{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the list edge router role attribute usage o k response
func (o *ListEdgeRouterRoleAttributeUsageOK) WithWWWAuthenticate(wWWAuthenticate []string) *ListEdgeRouterRoleAttributeUsageOK {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the list edge router role attribute usage o k response
func (o *ListEdgeRouterRoleAttributeUsageOK) SetWWWAuthenticate(wWWAuthenticate []string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the list edge router role attribute usage o k response
func (o *ListEdgeRouterRoleAttributeUsageOK) WithPayload(payload *rest_model.ListRoleAttributeUsageEnvelope) *ListEdgeRouterRoleAttributeUsageOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list edge router role attribute usage o k response
func (o *ListEdgeRouterRoleAttributeUsageOK) SetPayload(payload *rest_model.ListRoleAttributeUsageEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListEdgeRouterRoleAttributeUsageOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	var wWWAuthenticateIR []string
	for _, wWWAuthenticateI := range o.WWWAuthenticate {
		wWWAuthenticateIS := wWWAuthenticateI
		if wWWAuthenticateIS != "" {
			wWWAuthenticateIR = append(wWWAuthenticateIR, wWWAuthenticateIS)
		}
	}
	wWWAuthenticate := swag.JoinByFormat(wWWAuthenticateIR, "")
	if len(wWWAuthenticate) > 0 {
		hv := wWWAuthenticate[0]
		if hv != "" {
			rw.Header().Set("WWW-Authenticate", hv)
		}
	}

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListEdgeRouterRoleAttributeUsageBadRequestCode is the HTTP code returned for type ListEdgeRouterRoleAttributeUsageBadRequest
const ListEdgeRouterRoleAttributeUsageBadRequestCode int = 400

/*
ListEdgeRouterRoleAttributeUsageBadRequest The supplied request contains invalid fields or could not be parsed (json and non-json bodies). The error's code, message, and cause fields can be inspected for further information

swagger:response listEdgeRouterRoleAttributeUsageBadRequest
*/
type ListEdgeRouterRoleAttributeUsageBadRequest struct {
	/*Denotes different type of security token related information

	 */
	WWWAuthenticate []string `json:"WWW-Authenticate"`

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewListEdgeRouterRoleAttributeUsageBadRequest creates ListEdgeRouterRoleAttributeUsageBadRequest with default headers values
func NewListEdgeRouterRoleAttributeUsageBadRequest() *ListEdgeRouterRoleAttributeUsageBadRequest {

	return &ListEdgeRouterRoleAttributeUsageBadRequest{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the list edge router role attribute usage bad request response
func (o *ListEdgeRouterRoleAttributeUsageBadRequest) WithWWWAuthenticate(wWWAuthenticate []string) *ListEdgeRouterRoleAttributeUsageBadRequest {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the list edge router role attribute usage bad request response
func (o *ListEdgeRouterRoleAttributeUsageBadRequest) SetWWWAuthenticate(wWWAuthenticate []string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the list edge router role attribute usage bad request response
func (o *ListEdgeRouterRoleAttributeUsageBadRequest) WithPayload(payload *rest_model.APIErrorEnvelope) *ListEdgeRouterRoleAttributeUsageBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list edge router role attribute usage bad request response
func (o *ListEdgeRouterRoleAttributeUsageBadRequest) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListEdgeRouterRoleAttributeUsageBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	var wWWAuthenticateIR []string
	for _, wWWAuthenticateI := range o.WWWAuthenticate {
		wWWAuthenticateIS := wWWAuthenticateI
		if wWWAuthenticateIS != "" {
			wWWAuthenticateIR = append(wWWAuthenticateIR, wWWAuthenticateIS)
		}
	}
	wWWAuthenticate := swag.JoinByFormat(wWWAuthenticateIR, "")
	if len(wWWAuthenticate) > 0 {
		hv := wWWAuthenticate[0]
		if hv != "" {
			rw.Header().Set("WWW-Authenticate", hv)
		}
	}

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListEdgeRouterRoleAttributeUsageUnauthorizedCode is the HTTP code returned for type ListEdgeRouterRoleAttributeUsageUnauthorized
const ListEdgeRouterRoleAttributeUsageUnauthorizedCode int = 401

/*
ListEdgeRouterRoleAttributeUsageUnauthorized The supplied session does not have the correct access rights to request this resource

swagger:response listEdgeRouterRoleAttributeUsageUnauthorized
*/
type ListEdgeRouterRoleAttributeUsageUnauthorized struct {
	/*Denotes different type of security token related information

	 */
	WWWAuthenticate []string `json:"WWW-Authenticate"`

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewListEdgeRouterRoleAttributeUsageUnauthorized creates ListEdgeRouterRoleAttributeUsageUnauthorized with default headers values
func NewListEdgeRouterRoleAttributeUsageUnauthorized() *ListEdgeRouterRoleAttributeUsageUnauthorized {

	return &ListEdgeRouterRoleAttributeUsageUnauthorized{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the list edge router role attribute usage unauthorized response
func (o *ListEdgeRouterRoleAttributeUsageUnauthorized) WithWWWAuthenticate(wWWAuthenticate []string) *ListEdgeRouterRoleAttributeUsageUnauthorized {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the list edge router role attribute usage unauthorized response
func (o *ListEdgeRouterRoleAttributeUsageUnauthorized) SetWWWAuthenticate(wWWAuthenticate []string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the list edge router role attribute usage unauthorized response
func (o *ListEdgeRouterRoleAttributeUsageUnauthorized) WithPayload(payload *rest_model.APIErrorEnvelope) *ListEdgeRouterRoleAttributeUsageUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list edge router role attribute usage unauthorized response
func (o *ListEdgeRouterRoleAttributeUsageUnauthorized) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListEdgeRouterRoleAttributeUsageUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	var wWWAuthenticateIR []string
	for _, wWWAuthenticateI := range o.WWWAuthenticate {
		wWWAuthenticateIS := wWWAuthenticateI
		if wWWAuthenticateIS != "" {
			wWWAuthenticateIR = append(wWWAuthenticateIR, wWWAuthenticateIS)
		}
	}
	wWWAuthenticate := swag.JoinByFormat(wWWAuthenticateIR, "")
	if len(wWWAuthenticate) > 0 {
		hv := wWWAuthenticate[0]
		if hv != "" {
			rw.Header().Set("WWW-Authenticate", hv)
		}
	}

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListEdgeRouterRoleAttributeUsageTooManyRequestsCode is the HTTP code returned for type ListEdgeRouterRoleAttributeUsageTooManyRequests
const ListEdgeRouterRoleAttributeUsageTooManyRequestsCode int = 429

/*
ListEdgeRouterRoleAttributeUsageTooManyRequests The resource requested is rate limited and the rate limit has been exceeded

swagger:response listEdgeRouterRoleAttributeUsageTooManyRequests
*/
type ListEdgeRouterRoleAttributeUsageTooManyRequests struct {
	/*Denotes different type of security token related information

	 */
	WWWAuthenticate []string `json:"WWW-Authenticate"`

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewListEdgeRouterRoleAttributeUsageTooManyRequests creates ListEdgeRouterRoleAttributeUsageTooManyRequests with default headers values
func NewListEdgeRouterRoleAttributeUsageTooManyRequests() *ListEdgeRouterRoleAttributeUsageTooManyRequests {

	return &ListEdgeRouterRoleAttributeUsageTooManyRequests{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the list edge router role attribute usage too many requests response
func (o *ListEdgeRouterRoleAttributeUsageTooManyRequests) WithWWWAuthenticate(wWWAuthenticate []string) *ListEdgeRouterRoleAttributeUsageTooManyRequests {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the list edge router role attribute usage too many requests response
func (o *ListEdgeRouterRoleAttributeUsageTooManyRequests) SetWWWAuthenticate(wWWAuthenticate []string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the list edge router role attribute usage too many requests response
func (o *ListEdgeRouterRoleAttributeUsageTooManyRequests) WithPayload(payload *rest_model.APIErrorEnvelope) *ListEdgeRouterRoleAttributeUsageTooManyRequests {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list edge router role attribute usage too many requests response
func (o *ListEdgeRouterRoleAttributeUsageTooManyRequests) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListEdgeRouterRoleAttributeUsageTooManyRequests) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	var wWWAuthenticateIR []string
	for _, wWWAuthenticateI := range o.WWWAuthenticate {
		wWWAuthenticateIS := wWWAuthenticateI
		if wWWAuthenticateIS != "" {
			wWWAuthenticateIR = append(wWWAuthenticateIR, wWWAuthenticateIS)
		}
	}
	wWWAuthenticate := swag.JoinByFormat(wWWAuthenticateIR, "")
	if len(wWWAuthenticate) > 0 {
		hv := wWWAuthenticate[0]
		if hv != "" {
			rw.Header().Set("WWW-Authenticate", hv)
		}
	}

	rw.WriteHeader(429)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListEdgeRouterRoleAttributeUsageServiceUnavailableCode is the HTTP code returned for type ListEdgeRouterRoleAttributeUsageServiceUnavailable
const ListEdgeRouterRoleAttributeUsageServiceUnavailableCode int = 503

/*
ListEdgeRouterRoleAttributeUsageServiceUnavailable The request could not be completed due to the server being busy or in a temporarily bad state

swagger:response listEdgeRouterRoleAttributeUsageServiceUnavailable
*/
type ListEdgeRouterRoleAttributeUsageServiceUnavailable struct {
	/*Denotes different type of security token related information

	 */
	WWWAuthenticate []string `json:"WWW-Authenticate"`

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewListEdgeRouterRoleAttributeUsageServiceUnavailable creates ListEdgeRouterRoleAttributeUsageServiceUnavailable with default headers values
func NewListEdgeRouterRoleAttributeUsageServiceUnavailable() *ListEdgeRouterRoleAttributeUsageServiceUnavailable {

	return &ListEdgeRouterRoleAttributeUsageServiceUnavailable{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the list edge router role attribute usage service unavailable response
func (o *ListEdgeRouterRoleAttributeUsageServiceUnavailable) WithWWWAuthenticate(wWWAuthenticate []string) *ListEdgeRouterRoleAttributeUsageServiceUnavailable {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the list edge router role attribute usage service unavailable response
func (o *ListEdgeRouterRoleAttributeUsageServiceUnavailable) SetWWWAuthenticate(wWWAuthenticate []string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the list edge router role attribute usage service unavailable response
func (o *ListEdgeRouterRoleAttributeUsageServiceUnavailable) WithPayload(payload *rest_model.APIErrorEnvelope) *ListEdgeRouterRoleAttributeUsageServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list edge router role attribute usage service unavailable response
func (o *ListEdgeRouterRoleAttributeUsageServiceUnavailable) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListEdgeRouterRoleAttributeUsageServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	var wWWAuthenticateIR []string
	for _, wWWAuthenticateI := range o.WWWAuthenticate {
		wWWAuthenticateIS := wWWAuthenticateI
		if wWWAuthenticateIS != "" {
			wWWAuthenticateIR = append(wWWAuthenticateIR, wWWAuthenticateIS)
		}
	}
	wWWAuthenticate := swag.JoinByFormat(wWWAuthenticateIR, "")
	if len(wWWAuthenticate) > 0 {
		hv := wWWAuthenticate[0]
		if hv != "" {
			rw.Header().Set("WWW-Authenticate", hv)
		}
	}

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
