// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package informational

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	"github.com/openziti/edge-api/rest_model"
)

// ListEnumeratedRouterCapabilitiesOKCode is the HTTP code returned for type ListEnumeratedRouterCapabilitiesOK
const ListEnumeratedRouterCapabilitiesOKCode int = 200

/*
ListEnumeratedRouterCapabilitiesOK A typed and enumerated list of router capabilities

swagger:response listEnumeratedRouterCapabilitiesOK
*/
type ListEnumeratedRouterCapabilitiesOK struct {
	/*Denotes different type of security token related information

	 */
	WWWAuthenticate []string `json:"WWW-Authenticate"`

	/*
	  In: Body
	*/
	Payload *rest_model.ListEnumeratedRouterCapabilitiesEnvelope `json:"body,omitempty"`
}

// NewListEnumeratedRouterCapabilitiesOK creates ListEnumeratedRouterCapabilitiesOK with default headers values
func NewListEnumeratedRouterCapabilitiesOK() *ListEnumeratedRouterCapabilitiesOK {

	return &ListEnumeratedRouterCapabilitiesOK{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the list enumerated router capabilities o k response
func (o *ListEnumeratedRouterCapabilitiesOK) WithWWWAuthenticate(wWWAuthenticate []string) *ListEnumeratedRouterCapabilitiesOK {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the list enumerated router capabilities o k response
func (o *ListEnumeratedRouterCapabilitiesOK) SetWWWAuthenticate(wWWAuthenticate []string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the list enumerated router capabilities o k response
func (o *ListEnumeratedRouterCapabilitiesOK) WithPayload(payload *rest_model.ListEnumeratedRouterCapabilitiesEnvelope) *ListEnumeratedRouterCapabilitiesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list enumerated router capabilities o k response
func (o *ListEnumeratedRouterCapabilitiesOK) SetPayload(payload *rest_model.ListEnumeratedRouterCapabilitiesEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListEnumeratedRouterCapabilitiesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	var wWWAuthenticateIR []string
	for _, wWWAuthenticateI := range o.WWWAuthenticate {
		wWWAuthenticateIS := wWWAuthenticateI
		if wWWAuthenticateIS != "" {
			wWWAuthenticateIR = append(wWWAuthenticateIR, wWWAuthenticateIS)
		}
	}
	wWWAuthenticate := swag.JoinByFormat(wWWAuthenticateIR, "")
	if len(wWWAuthenticate) > 0 {
		hv := wWWAuthenticate[0]
		if hv != "" {
			rw.Header().Set("WWW-Authenticate", hv)
		}
	}

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListEnumeratedRouterCapabilitiesUnauthorizedCode is the HTTP code returned for type ListEnumeratedRouterCapabilitiesUnauthorized
const ListEnumeratedRouterCapabilitiesUnauthorizedCode int = 401

/*
ListEnumeratedRouterCapabilitiesUnauthorized The supplied session does not have the correct access rights to request this resource

swagger:response listEnumeratedRouterCapabilitiesUnauthorized
*/
type ListEnumeratedRouterCapabilitiesUnauthorized struct {
	/*Denotes different type of security token related information

	 */
	WWWAuthenticate []string `json:"WWW-Authenticate"`

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewListEnumeratedRouterCapabilitiesUnauthorized creates ListEnumeratedRouterCapabilitiesUnauthorized with default headers values
func NewListEnumeratedRouterCapabilitiesUnauthorized() *ListEnumeratedRouterCapabilitiesUnauthorized {

	return &ListEnumeratedRouterCapabilitiesUnauthorized{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the list enumerated router capabilities unauthorized response
func (o *ListEnumeratedRouterCapabilitiesUnauthorized) WithWWWAuthenticate(wWWAuthenticate []string) *ListEnumeratedRouterCapabilitiesUnauthorized {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the list enumerated router capabilities unauthorized response
func (o *ListEnumeratedRouterCapabilitiesUnauthorized) SetWWWAuthenticate(wWWAuthenticate []string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the list enumerated router capabilities unauthorized response
func (o *ListEnumeratedRouterCapabilitiesUnauthorized) WithPayload(payload *rest_model.APIErrorEnvelope) *ListEnumeratedRouterCapabilitiesUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list enumerated router capabilities unauthorized response
func (o *ListEnumeratedRouterCapabilitiesUnauthorized) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListEnumeratedRouterCapabilitiesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	var wWWAuthenticateIR []string
	for _, wWWAuthenticateI := range o.WWWAuthenticate {
		wWWAuthenticateIS := wWWAuthenticateI
		if wWWAuthenticateIS != "" {
			wWWAuthenticateIR = append(wWWAuthenticateIR, wWWAuthenticateIS)
		}
	}
	wWWAuthenticate := swag.JoinByFormat(wWWAuthenticateIR, "")
	if len(wWWAuthenticate) > 0 {
		hv := wWWAuthenticate[0]
		if hv != "" {
			rw.Header().Set("WWW-Authenticate", hv)
		}
	}

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListEnumeratedRouterCapabilitiesTooManyRequestsCode is the HTTP code returned for type ListEnumeratedRouterCapabilitiesTooManyRequests
const ListEnumeratedRouterCapabilitiesTooManyRequestsCode int = 429

/*
ListEnumeratedRouterCapabilitiesTooManyRequests The resource requested is rate limited and the rate limit has been exceeded

swagger:response listEnumeratedRouterCapabilitiesTooManyRequests
*/
type ListEnumeratedRouterCapabilitiesTooManyRequests struct {
	/*Denotes different type of security token related information

	 */
	WWWAuthenticate []string `json:"WWW-Authenticate"`

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewListEnumeratedRouterCapabilitiesTooManyRequests creates ListEnumeratedRouterCapabilitiesTooManyRequests with default headers values
func NewListEnumeratedRouterCapabilitiesTooManyRequests() *ListEnumeratedRouterCapabilitiesTooManyRequests {

	return &ListEnumeratedRouterCapabilitiesTooManyRequests{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the list enumerated router capabilities too many requests response
func (o *ListEnumeratedRouterCapabilitiesTooManyRequests) WithWWWAuthenticate(wWWAuthenticate []string) *ListEnumeratedRouterCapabilitiesTooManyRequests {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the list enumerated router capabilities too many requests response
func (o *ListEnumeratedRouterCapabilitiesTooManyRequests) SetWWWAuthenticate(wWWAuthenticate []string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the list enumerated router capabilities too many requests response
func (o *ListEnumeratedRouterCapabilitiesTooManyRequests) WithPayload(payload *rest_model.APIErrorEnvelope) *ListEnumeratedRouterCapabilitiesTooManyRequests {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list enumerated router capabilities too many requests response
func (o *ListEnumeratedRouterCapabilitiesTooManyRequests) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListEnumeratedRouterCapabilitiesTooManyRequests) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	var wWWAuthenticateIR []string
	for _, wWWAuthenticateI := range o.WWWAuthenticate {
		wWWAuthenticateIS := wWWAuthenticateI
		if wWWAuthenticateIS != "" {
			wWWAuthenticateIR = append(wWWAuthenticateIR, wWWAuthenticateIS)
		}
	}
	wWWAuthenticate := swag.JoinByFormat(wWWAuthenticateIR, "")
	if len(wWWAuthenticate) > 0 {
		hv := wWWAuthenticate[0]
		if hv != "" {
			rw.Header().Set("WWW-Authenticate", hv)
		}
	}

	rw.WriteHeader(429)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListEnumeratedRouterCapabilitiesServiceUnavailableCode is the HTTP code returned for type ListEnumeratedRouterCapabilitiesServiceUnavailable
const ListEnumeratedRouterCapabilitiesServiceUnavailableCode int = 503

/*
ListEnumeratedRouterCapabilitiesServiceUnavailable The request could not be completed due to the server being busy or in a temporarily bad state

swagger:response listEnumeratedRouterCapabilitiesServiceUnavailable
*/
type ListEnumeratedRouterCapabilitiesServiceUnavailable struct {
	/*Denotes different type of security token related information

	 */
	WWWAuthenticate []string `json:"WWW-Authenticate"`

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewListEnumeratedRouterCapabilitiesServiceUnavailable creates ListEnumeratedRouterCapabilitiesServiceUnavailable with default headers values
func NewListEnumeratedRouterCapabilitiesServiceUnavailable() *ListEnumeratedRouterCapabilitiesServiceUnavailable {

	return &ListEnumeratedRouterCapabilitiesServiceUnavailable{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the list enumerated router capabilities service unavailable response
func (o *ListEnumeratedRouterCapabilitiesServiceUnavailable) WithWWWAuthenticate(wWWAuthenticate []string) *ListEnumeratedRouterCapabilitiesServiceUnavailable {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the list enumerated router capabilities service unavailable response
func (o *ListEnumeratedRouterCapabilitiesServiceUnavailable) SetWWWAuthenticate(wWWAuthenticate []string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the list enumerated router capabilities service unavailable response
func (o *ListEnumeratedRouterCapabilitiesServiceUnavailable) WithPayload(payload *rest_model.APIErrorEnvelope) *ListEnumeratedRouterCapabilitiesServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list enumerated router capabilities service unavailable response
func (o *ListEnumeratedRouterCapabilitiesServiceUnavailable) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListEnumeratedRouterCapabilitiesServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	var wWWAuthenticateIR []string
	for _, wWWAuthenticateI := range o.WWWAuthenticate {
		wWWAuthenticateIS := wWWAuthenticateI
		if wWWAuthenticateIS != "" {
			wWWAuthenticateIR = append(wWWAuthenticateIR, wWWAuthenticateIS)
		}
	}
	wWWAuthenticate := swag.JoinByFormat(wWWAuthenticateIR, "")
	if len(wWWAuthenticate) > 0 {
		hv := wWWAuthenticate[0]
		if hv != "" {
			rw.Header().Set("WWW-Authenticate", hv)
		}
	}

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
