// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package settings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	"github.com/openziti/edge-api/rest_model"
)

// CreateControllerSettingCreatedCode is the HTTP code returned for type CreateControllerSettingCreated
const CreateControllerSettingCreatedCode int = 201

/*
CreateControllerSettingCreated The create request was successful and the resource has been added at the following location

swagger:response createControllerSettingCreated
*/
type CreateControllerSettingCreated struct {
	/*Denotes different type of security token related information

	 */
	WWWAuthenticate []string `json:"WWW-Authenticate"`

	/*
	  In: Body
	*/
	Payload *rest_model.CreateEnvelope `json:"body,omitempty"`
}

// NewCreateControllerSettingCreated creates CreateControllerSettingCreated with default headers values
func NewCreateControllerSettingCreated() *CreateControllerSettingCreated {

	return &CreateControllerSettingCreated{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the create controller setting created response
func (o *CreateControllerSettingCreated) WithWWWAuthenticate(wWWAuthenticate []string) *CreateControllerSettingCreated {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the create controller setting created response
func (o *CreateControllerSettingCreated) SetWWWAuthenticate(wWWAuthenticate []string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the create controller setting created response
func (o *CreateControllerSettingCreated) WithPayload(payload *rest_model.CreateEnvelope) *CreateControllerSettingCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create controller setting created response
func (o *CreateControllerSettingCreated) SetPayload(payload *rest_model.CreateEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateControllerSettingCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	var wWWAuthenticateIR []string
	for _, wWWAuthenticateI := range o.WWWAuthenticate {
		wWWAuthenticateIS := wWWAuthenticateI
		if wWWAuthenticateIS != "" {
			wWWAuthenticateIR = append(wWWAuthenticateIR, wWWAuthenticateIS)
		}
	}
	wWWAuthenticate := swag.JoinByFormat(wWWAuthenticateIR, "")
	if len(wWWAuthenticate) > 0 {
		hv := wWWAuthenticate[0]
		if hv != "" {
			rw.Header().Set("WWW-Authenticate", hv)
		}
	}

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateControllerSettingBadRequestCode is the HTTP code returned for type CreateControllerSettingBadRequest
const CreateControllerSettingBadRequestCode int = 400

/*
CreateControllerSettingBadRequest The supplied request contains invalid fields or could not be parsed (json and non-json bodies). The error's code, message, and cause fields can be inspected for further information

swagger:response createControllerSettingBadRequest
*/
type CreateControllerSettingBadRequest struct {
	/*Denotes different type of security token related information

	 */
	WWWAuthenticate []string `json:"WWW-Authenticate"`

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewCreateControllerSettingBadRequest creates CreateControllerSettingBadRequest with default headers values
func NewCreateControllerSettingBadRequest() *CreateControllerSettingBadRequest {

	return &CreateControllerSettingBadRequest{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the create controller setting bad request response
func (o *CreateControllerSettingBadRequest) WithWWWAuthenticate(wWWAuthenticate []string) *CreateControllerSettingBadRequest {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the create controller setting bad request response
func (o *CreateControllerSettingBadRequest) SetWWWAuthenticate(wWWAuthenticate []string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the create controller setting bad request response
func (o *CreateControllerSettingBadRequest) WithPayload(payload *rest_model.APIErrorEnvelope) *CreateControllerSettingBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create controller setting bad request response
func (o *CreateControllerSettingBadRequest) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateControllerSettingBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	var wWWAuthenticateIR []string
	for _, wWWAuthenticateI := range o.WWWAuthenticate {
		wWWAuthenticateIS := wWWAuthenticateI
		if wWWAuthenticateIS != "" {
			wWWAuthenticateIR = append(wWWAuthenticateIR, wWWAuthenticateIS)
		}
	}
	wWWAuthenticate := swag.JoinByFormat(wWWAuthenticateIR, "")
	if len(wWWAuthenticate) > 0 {
		hv := wWWAuthenticate[0]
		if hv != "" {
			rw.Header().Set("WWW-Authenticate", hv)
		}
	}

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateControllerSettingUnauthorizedCode is the HTTP code returned for type CreateControllerSettingUnauthorized
const CreateControllerSettingUnauthorizedCode int = 401

/*
CreateControllerSettingUnauthorized The supplied session does not have the correct access rights to request this resource

swagger:response createControllerSettingUnauthorized
*/
type CreateControllerSettingUnauthorized struct {
	/*Denotes different type of security token related information

	 */
	WWWAuthenticate []string `json:"WWW-Authenticate"`

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewCreateControllerSettingUnauthorized creates CreateControllerSettingUnauthorized with default headers values
func NewCreateControllerSettingUnauthorized() *CreateControllerSettingUnauthorized {

	return &CreateControllerSettingUnauthorized{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the create controller setting unauthorized response
func (o *CreateControllerSettingUnauthorized) WithWWWAuthenticate(wWWAuthenticate []string) *CreateControllerSettingUnauthorized {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the create controller setting unauthorized response
func (o *CreateControllerSettingUnauthorized) SetWWWAuthenticate(wWWAuthenticate []string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the create controller setting unauthorized response
func (o *CreateControllerSettingUnauthorized) WithPayload(payload *rest_model.APIErrorEnvelope) *CreateControllerSettingUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create controller setting unauthorized response
func (o *CreateControllerSettingUnauthorized) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateControllerSettingUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	var wWWAuthenticateIR []string
	for _, wWWAuthenticateI := range o.WWWAuthenticate {
		wWWAuthenticateIS := wWWAuthenticateI
		if wWWAuthenticateIS != "" {
			wWWAuthenticateIR = append(wWWAuthenticateIR, wWWAuthenticateIS)
		}
	}
	wWWAuthenticate := swag.JoinByFormat(wWWAuthenticateIR, "")
	if len(wWWAuthenticate) > 0 {
		hv := wWWAuthenticate[0]
		if hv != "" {
			rw.Header().Set("WWW-Authenticate", hv)
		}
	}

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateControllerSettingTooManyRequestsCode is the HTTP code returned for type CreateControllerSettingTooManyRequests
const CreateControllerSettingTooManyRequestsCode int = 429

/*
CreateControllerSettingTooManyRequests The resource requested is rate limited and the rate limit has been exceeded

swagger:response createControllerSettingTooManyRequests
*/
type CreateControllerSettingTooManyRequests struct {
	/*Denotes different type of security token related information

	 */
	WWWAuthenticate []string `json:"WWW-Authenticate"`

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewCreateControllerSettingTooManyRequests creates CreateControllerSettingTooManyRequests with default headers values
func NewCreateControllerSettingTooManyRequests() *CreateControllerSettingTooManyRequests {

	return &CreateControllerSettingTooManyRequests{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the create controller setting too many requests response
func (o *CreateControllerSettingTooManyRequests) WithWWWAuthenticate(wWWAuthenticate []string) *CreateControllerSettingTooManyRequests {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the create controller setting too many requests response
func (o *CreateControllerSettingTooManyRequests) SetWWWAuthenticate(wWWAuthenticate []string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the create controller setting too many requests response
func (o *CreateControllerSettingTooManyRequests) WithPayload(payload *rest_model.APIErrorEnvelope) *CreateControllerSettingTooManyRequests {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create controller setting too many requests response
func (o *CreateControllerSettingTooManyRequests) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateControllerSettingTooManyRequests) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	var wWWAuthenticateIR []string
	for _, wWWAuthenticateI := range o.WWWAuthenticate {
		wWWAuthenticateIS := wWWAuthenticateI
		if wWWAuthenticateIS != "" {
			wWWAuthenticateIR = append(wWWAuthenticateIR, wWWAuthenticateIS)
		}
	}
	wWWAuthenticate := swag.JoinByFormat(wWWAuthenticateIR, "")
	if len(wWWAuthenticate) > 0 {
		hv := wWWAuthenticate[0]
		if hv != "" {
			rw.Header().Set("WWW-Authenticate", hv)
		}
	}

	rw.WriteHeader(429)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
