// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package current_api_session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	"github.com/openziti/edge-api/rest_model"
)

// ListServiceUpdatesOKCode is the HTTP code returned for type ListServiceUpdatesOK
const ListServiceUpdatesOKCode int = 200

/*
ListServiceUpdatesOK Data indicating necessary service updates

swagger:response listServiceUpdatesOK
*/
type ListServiceUpdatesOK struct {
	/*Denotes different type of security token related information

	 */
	WWWAuthenticate []string `json:"WWW-Authenticate"`

	/*
	  In: Body
	*/
	Payload *rest_model.ListCurrentAPISessionServiceUpdatesEnvelope `json:"body,omitempty"`
}

// NewListServiceUpdatesOK creates ListServiceUpdatesOK with default headers values
func NewListServiceUpdatesOK() *ListServiceUpdatesOK {

	return &ListServiceUpdatesOK{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the list service updates o k response
func (o *ListServiceUpdatesOK) WithWWWAuthenticate(wWWAuthenticate []string) *ListServiceUpdatesOK {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the list service updates o k response
func (o *ListServiceUpdatesOK) SetWWWAuthenticate(wWWAuthenticate []string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the list service updates o k response
func (o *ListServiceUpdatesOK) WithPayload(payload *rest_model.ListCurrentAPISessionServiceUpdatesEnvelope) *ListServiceUpdatesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list service updates o k response
func (o *ListServiceUpdatesOK) SetPayload(payload *rest_model.ListCurrentAPISessionServiceUpdatesEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListServiceUpdatesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	var wWWAuthenticateIR []string
	for _, wWWAuthenticateI := range o.WWWAuthenticate {
		wWWAuthenticateIS := wWWAuthenticateI
		if wWWAuthenticateIS != "" {
			wWWAuthenticateIR = append(wWWAuthenticateIR, wWWAuthenticateIS)
		}
	}
	wWWAuthenticate := swag.JoinByFormat(wWWAuthenticateIR, "")
	if len(wWWAuthenticate) > 0 {
		hv := wWWAuthenticate[0]
		if hv != "" {
			rw.Header().Set("WWW-Authenticate", hv)
		}
	}

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListServiceUpdatesUnauthorizedCode is the HTTP code returned for type ListServiceUpdatesUnauthorized
const ListServiceUpdatesUnauthorizedCode int = 401

/*
ListServiceUpdatesUnauthorized The supplied session does not have the correct access rights to request this resource

swagger:response listServiceUpdatesUnauthorized
*/
type ListServiceUpdatesUnauthorized struct {
	/*Denotes different type of security token related information

	 */
	WWWAuthenticate []string `json:"WWW-Authenticate"`

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewListServiceUpdatesUnauthorized creates ListServiceUpdatesUnauthorized with default headers values
func NewListServiceUpdatesUnauthorized() *ListServiceUpdatesUnauthorized {

	return &ListServiceUpdatesUnauthorized{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the list service updates unauthorized response
func (o *ListServiceUpdatesUnauthorized) WithWWWAuthenticate(wWWAuthenticate []string) *ListServiceUpdatesUnauthorized {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the list service updates unauthorized response
func (o *ListServiceUpdatesUnauthorized) SetWWWAuthenticate(wWWAuthenticate []string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the list service updates unauthorized response
func (o *ListServiceUpdatesUnauthorized) WithPayload(payload *rest_model.APIErrorEnvelope) *ListServiceUpdatesUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list service updates unauthorized response
func (o *ListServiceUpdatesUnauthorized) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListServiceUpdatesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	var wWWAuthenticateIR []string
	for _, wWWAuthenticateI := range o.WWWAuthenticate {
		wWWAuthenticateIS := wWWAuthenticateI
		if wWWAuthenticateIS != "" {
			wWWAuthenticateIR = append(wWWAuthenticateIR, wWWAuthenticateIS)
		}
	}
	wWWAuthenticate := swag.JoinByFormat(wWWAuthenticateIR, "")
	if len(wWWAuthenticate) > 0 {
		hv := wWWAuthenticate[0]
		if hv != "" {
			rw.Header().Set("WWW-Authenticate", hv)
		}
	}

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListServiceUpdatesTooManyRequestsCode is the HTTP code returned for type ListServiceUpdatesTooManyRequests
const ListServiceUpdatesTooManyRequestsCode int = 429

/*
ListServiceUpdatesTooManyRequests The resource requested is rate limited and the rate limit has been exceeded

swagger:response listServiceUpdatesTooManyRequests
*/
type ListServiceUpdatesTooManyRequests struct {
	/*Denotes different type of security token related information

	 */
	WWWAuthenticate []string `json:"WWW-Authenticate"`

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewListServiceUpdatesTooManyRequests creates ListServiceUpdatesTooManyRequests with default headers values
func NewListServiceUpdatesTooManyRequests() *ListServiceUpdatesTooManyRequests {

	return &ListServiceUpdatesTooManyRequests{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the list service updates too many requests response
func (o *ListServiceUpdatesTooManyRequests) WithWWWAuthenticate(wWWAuthenticate []string) *ListServiceUpdatesTooManyRequests {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the list service updates too many requests response
func (o *ListServiceUpdatesTooManyRequests) SetWWWAuthenticate(wWWAuthenticate []string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the list service updates too many requests response
func (o *ListServiceUpdatesTooManyRequests) WithPayload(payload *rest_model.APIErrorEnvelope) *ListServiceUpdatesTooManyRequests {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list service updates too many requests response
func (o *ListServiceUpdatesTooManyRequests) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListServiceUpdatesTooManyRequests) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	var wWWAuthenticateIR []string
	for _, wWWAuthenticateI := range o.WWWAuthenticate {
		wWWAuthenticateIS := wWWAuthenticateI
		if wWWAuthenticateIS != "" {
			wWWAuthenticateIR = append(wWWAuthenticateIR, wWWAuthenticateIS)
		}
	}
	wWWAuthenticate := swag.JoinByFormat(wWWAuthenticateIR, "")
	if len(wWWAuthenticate) > 0 {
		hv := wWWAuthenticate[0]
		if hv != "" {
			rw.Header().Set("WWW-Authenticate", hv)
		}
	}

	rw.WriteHeader(429)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListServiceUpdatesServiceUnavailableCode is the HTTP code returned for type ListServiceUpdatesServiceUnavailable
const ListServiceUpdatesServiceUnavailableCode int = 503

/*
ListServiceUpdatesServiceUnavailable The request could not be completed due to the server being busy or in a temporarily bad state

swagger:response listServiceUpdatesServiceUnavailable
*/
type ListServiceUpdatesServiceUnavailable struct {
	/*Denotes different type of security token related information

	 */
	WWWAuthenticate []string `json:"WWW-Authenticate"`

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewListServiceUpdatesServiceUnavailable creates ListServiceUpdatesServiceUnavailable with default headers values
func NewListServiceUpdatesServiceUnavailable() *ListServiceUpdatesServiceUnavailable {

	return &ListServiceUpdatesServiceUnavailable{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the list service updates service unavailable response
func (o *ListServiceUpdatesServiceUnavailable) WithWWWAuthenticate(wWWAuthenticate []string) *ListServiceUpdatesServiceUnavailable {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the list service updates service unavailable response
func (o *ListServiceUpdatesServiceUnavailable) SetWWWAuthenticate(wWWAuthenticate []string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the list service updates service unavailable response
func (o *ListServiceUpdatesServiceUnavailable) WithPayload(payload *rest_model.APIErrorEnvelope) *ListServiceUpdatesServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list service updates service unavailable response
func (o *ListServiceUpdatesServiceUnavailable) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListServiceUpdatesServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	var wWWAuthenticateIR []string
	for _, wWWAuthenticateI := range o.WWWAuthenticate {
		wWWAuthenticateIS := wWWAuthenticateI
		if wWWAuthenticateIS != "" {
			wWWAuthenticateIR = append(wWWAuthenticateIR, wWWAuthenticateIS)
		}
	}
	wWWAuthenticate := swag.JoinByFormat(wWWAuthenticateIR, "")
	if len(wWWAuthenticate) > 0 {
		hv := wWWAuthenticate[0]
		if hv != "" {
			rw.Header().Set("WWW-Authenticate", hv)
		}
	}

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
