// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package database

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	"github.com/openziti/edge-api/rest_model"
)

// FixDataIntegrityAcceptedCode is the HTTP code returned for type FixDataIntegrityAccepted
const FixDataIntegrityAcceptedCode int = 202

/*
FixDataIntegrityAccepted Base empty response

swagger:response fixDataIntegrityAccepted
*/
type FixDataIntegrityAccepted struct {
	/*Denotes different type of security token related information

	 */
	WWWAuthenticate []string `json:"WWW-Authenticate"`

	/*
	  In: Body
	*/
	Payload *rest_model.Empty `json:"body,omitempty"`
}

// NewFixDataIntegrityAccepted creates FixDataIntegrityAccepted with default headers values
func NewFixDataIntegrityAccepted() *FixDataIntegrityAccepted {

	return &FixDataIntegrityAccepted{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the fix data integrity accepted response
func (o *FixDataIntegrityAccepted) WithWWWAuthenticate(wWWAuthenticate []string) *FixDataIntegrityAccepted {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the fix data integrity accepted response
func (o *FixDataIntegrityAccepted) SetWWWAuthenticate(wWWAuthenticate []string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the fix data integrity accepted response
func (o *FixDataIntegrityAccepted) WithPayload(payload *rest_model.Empty) *FixDataIntegrityAccepted {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fix data integrity accepted response
func (o *FixDataIntegrityAccepted) SetPayload(payload *rest_model.Empty) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FixDataIntegrityAccepted) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	var wWWAuthenticateIR []string
	for _, wWWAuthenticateI := range o.WWWAuthenticate {
		wWWAuthenticateIS := wWWAuthenticateI
		if wWWAuthenticateIS != "" {
			wWWAuthenticateIR = append(wWWAuthenticateIR, wWWAuthenticateIS)
		}
	}
	wWWAuthenticate := swag.JoinByFormat(wWWAuthenticateIR, "")
	if len(wWWAuthenticate) > 0 {
		hv := wWWAuthenticate[0]
		if hv != "" {
			rw.Header().Set("WWW-Authenticate", hv)
		}
	}

	rw.WriteHeader(202)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FixDataIntegrityUnauthorizedCode is the HTTP code returned for type FixDataIntegrityUnauthorized
const FixDataIntegrityUnauthorizedCode int = 401

/*
FixDataIntegrityUnauthorized The supplied session does not have the correct access rights to request this resource

swagger:response fixDataIntegrityUnauthorized
*/
type FixDataIntegrityUnauthorized struct {
	/*Denotes different type of security token related information

	 */
	WWWAuthenticate []string `json:"WWW-Authenticate"`

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewFixDataIntegrityUnauthorized creates FixDataIntegrityUnauthorized with default headers values
func NewFixDataIntegrityUnauthorized() *FixDataIntegrityUnauthorized {

	return &FixDataIntegrityUnauthorized{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the fix data integrity unauthorized response
func (o *FixDataIntegrityUnauthorized) WithWWWAuthenticate(wWWAuthenticate []string) *FixDataIntegrityUnauthorized {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the fix data integrity unauthorized response
func (o *FixDataIntegrityUnauthorized) SetWWWAuthenticate(wWWAuthenticate []string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the fix data integrity unauthorized response
func (o *FixDataIntegrityUnauthorized) WithPayload(payload *rest_model.APIErrorEnvelope) *FixDataIntegrityUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fix data integrity unauthorized response
func (o *FixDataIntegrityUnauthorized) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FixDataIntegrityUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	var wWWAuthenticateIR []string
	for _, wWWAuthenticateI := range o.WWWAuthenticate {
		wWWAuthenticateIS := wWWAuthenticateI
		if wWWAuthenticateIS != "" {
			wWWAuthenticateIR = append(wWWAuthenticateIR, wWWAuthenticateIS)
		}
	}
	wWWAuthenticate := swag.JoinByFormat(wWWAuthenticateIR, "")
	if len(wWWAuthenticate) > 0 {
		hv := wWWAuthenticate[0]
		if hv != "" {
			rw.Header().Set("WWW-Authenticate", hv)
		}
	}

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FixDataIntegrityTooManyRequestsCode is the HTTP code returned for type FixDataIntegrityTooManyRequests
const FixDataIntegrityTooManyRequestsCode int = 429

/*
FixDataIntegrityTooManyRequests The resource requested is rate limited and the rate limit has been exceeded

swagger:response fixDataIntegrityTooManyRequests
*/
type FixDataIntegrityTooManyRequests struct {
	/*Denotes different type of security token related information

	 */
	WWWAuthenticate []string `json:"WWW-Authenticate"`

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewFixDataIntegrityTooManyRequests creates FixDataIntegrityTooManyRequests with default headers values
func NewFixDataIntegrityTooManyRequests() *FixDataIntegrityTooManyRequests {

	return &FixDataIntegrityTooManyRequests{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the fix data integrity too many requests response
func (o *FixDataIntegrityTooManyRequests) WithWWWAuthenticate(wWWAuthenticate []string) *FixDataIntegrityTooManyRequests {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the fix data integrity too many requests response
func (o *FixDataIntegrityTooManyRequests) SetWWWAuthenticate(wWWAuthenticate []string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the fix data integrity too many requests response
func (o *FixDataIntegrityTooManyRequests) WithPayload(payload *rest_model.APIErrorEnvelope) *FixDataIntegrityTooManyRequests {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fix data integrity too many requests response
func (o *FixDataIntegrityTooManyRequests) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FixDataIntegrityTooManyRequests) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	var wWWAuthenticateIR []string
	for _, wWWAuthenticateI := range o.WWWAuthenticate {
		wWWAuthenticateIS := wWWAuthenticateI
		if wWWAuthenticateIS != "" {
			wWWAuthenticateIR = append(wWWAuthenticateIR, wWWAuthenticateIS)
		}
	}
	wWWAuthenticate := swag.JoinByFormat(wWWAuthenticateIR, "")
	if len(wWWAuthenticate) > 0 {
		hv := wWWAuthenticate[0]
		if hv != "" {
			rw.Header().Set("WWW-Authenticate", hv)
		}
	}

	rw.WriteHeader(429)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
