// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package ascode

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewImportAscodeParams creates a new ImportAscodeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewImportAscodeParams() *ImportAscodeParams {
	return &ImportAscodeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewImportAscodeParamsWithTimeout creates a new ImportAscodeParams object
// with the ability to set a timeout on a request.
func NewImportAscodeParamsWithTimeout(timeout time.Duration) *ImportAscodeParams {
	return &ImportAscodeParams{
		timeout: timeout,
	}
}

// NewImportAscodeParamsWithContext creates a new ImportAscodeParams object
// with the ability to set a context for a request.
func NewImportAscodeParamsWithContext(ctx context.Context) *ImportAscodeParams {
	return &ImportAscodeParams{
		Context: ctx,
	}
}

// NewImportAscodeParamsWithHTTPClient creates a new ImportAscodeParams object
// with the ability to set a custom HTTPClient for a request.
func NewImportAscodeParamsWithHTTPClient(client *http.Client) *ImportAscodeParams {
	return &ImportAscodeParams{
		HTTPClient: client,
	}
}

/* ImportAscodeParams contains all the parameters to send to the API endpoint
   for the import ascode operation.

   Typically these are written to a http.Request.
*/
type ImportAscodeParams struct {

	/* DryRun.

	   If true, the import is validated but not persisted
	*/
	DryRun *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the import ascode params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ImportAscodeParams) WithDefaults() *ImportAscodeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the import ascode params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ImportAscodeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the import ascode params
func (o *ImportAscodeParams) WithTimeout(timeout time.Duration) *ImportAscodeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the import ascode params
func (o *ImportAscodeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the import ascode params
func (o *ImportAscodeParams) WithContext(ctx context.Context) *ImportAscodeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the import ascode params
func (o *ImportAscodeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the import ascode params
func (o *ImportAscodeParams) WithHTTPClient(client *http.Client) *ImportAscodeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the import ascode params
func (o *ImportAscodeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDryRun adds the dryRun to the import ascode params
func (o *ImportAscodeParams) WithDryRun(dryRun *bool) *ImportAscodeParams {
	o.SetDryRun(dryRun)
	return o
}

// SetDryRun adds the dryRun to the import ascode params
func (o *ImportAscodeParams) SetDryRun(dryRun *bool) {
	o.DryRun = dryRun
}

// WriteToRequest writes these params to a swagger request
func (o *ImportAscodeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.DryRun != nil {

		// query param dryRun
		var qrDryRun bool

		if o.DryRun != nil {
			qrDryRun = *o.DryRun
		}
		qDryRun := swag.FormatBool(qrDryRun)
		if qDryRun != "" {

			if err := r.SetQueryParam("dryRun", qDryRun); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
