// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package rest_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// RevocationTypeEnum revocation type enum
//
// swagger:model revocationTypeEnum
type RevocationTypeEnum string

func NewRevocationTypeEnum(value RevocationTypeEnum) *RevocationTypeEnum {
	return &value
}

// Pointer returns a pointer to a freshly-allocated RevocationTypeEnum.
func (m RevocationTypeEnum) Pointer() *RevocationTypeEnum {
	return &m
}

const (

	// RevocationTypeEnumJTI captures enum value "JTI"
	RevocationTypeEnumJTI RevocationTypeEnum = "JTI"

	// RevocationTypeEnumIDENTITY captures enum value "IDENTITY"
	RevocationTypeEnumIDENTITY RevocationTypeEnum = "IDENTITY"

	// RevocationTypeEnumAPISESSION captures enum value "API_SESSION"
	RevocationTypeEnumAPISESSION RevocationTypeEnum = "API_SESSION"
)

// for schema
var revocationTypeEnumEnum []any

func init() {
	var res []RevocationTypeEnum
	if err := json.Unmarshal([]byte(`["JTI","IDENTITY","API_SESSION"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		revocationTypeEnumEnum = append(revocationTypeEnumEnum, v)
	}
}

func (m RevocationTypeEnum) validateRevocationTypeEnumEnum(path, location string, value RevocationTypeEnum) error {
	if err := validate.EnumCase(path, location, value, revocationTypeEnumEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this revocation type enum
func (m RevocationTypeEnum) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateRevocationTypeEnumEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this revocation type enum based on context it is used
func (m RevocationTypeEnum) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
