// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package enroll

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	"github.com/openziti/edge-api/rest_model"
)

// EnrollOttCaOKCode is the HTTP code returned for type EnrollOttCaOK
const EnrollOttCaOKCode int = 200

/*
EnrollOttCaOK Base empty response

swagger:response enrollOttCaOK
*/
type EnrollOttCaOK struct {
	/*Denotes different type of security token related information

	 */
	WWWAuthenticate []string `json:"WWW-Authenticate"`

	/*
	  In: Body
	*/
	Payload *rest_model.Empty `json:"body,omitempty"`
}

// NewEnrollOttCaOK creates EnrollOttCaOK with default headers values
func NewEnrollOttCaOK() *EnrollOttCaOK {

	return &EnrollOttCaOK{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the enroll ott ca o k response
func (o *EnrollOttCaOK) WithWWWAuthenticate(wWWAuthenticate []string) *EnrollOttCaOK {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the enroll ott ca o k response
func (o *EnrollOttCaOK) SetWWWAuthenticate(wWWAuthenticate []string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the enroll ott ca o k response
func (o *EnrollOttCaOK) WithPayload(payload *rest_model.Empty) *EnrollOttCaOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the enroll ott ca o k response
func (o *EnrollOttCaOK) SetPayload(payload *rest_model.Empty) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *EnrollOttCaOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	var wWWAuthenticateIR []string
	for _, wWWAuthenticateI := range o.WWWAuthenticate {
		wWWAuthenticateIS := wWWAuthenticateI
		if wWWAuthenticateIS != "" {
			wWWAuthenticateIR = append(wWWAuthenticateIR, wWWAuthenticateIS)
		}
	}
	wWWAuthenticate := swag.JoinByFormat(wWWAuthenticateIR, "")
	if len(wWWAuthenticate) > 0 {
		hv := wWWAuthenticate[0]
		if hv != "" {
			rw.Header().Set("WWW-Authenticate", hv)
		}
	}

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// EnrollOttCaBadRequestCode is the HTTP code returned for type EnrollOttCaBadRequest
const EnrollOttCaBadRequestCode int = 400

/*
EnrollOttCaBadRequest The supplied request contains invalid fields or could not be parsed (json and non-json bodies). The error's code, message, and cause fields can be inspected for further information

swagger:response enrollOttCaBadRequest
*/
type EnrollOttCaBadRequest struct {
	/*Denotes different type of security token related information

	 */
	WWWAuthenticate []string `json:"WWW-Authenticate"`

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewEnrollOttCaBadRequest creates EnrollOttCaBadRequest with default headers values
func NewEnrollOttCaBadRequest() *EnrollOttCaBadRequest {

	return &EnrollOttCaBadRequest{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the enroll ott ca bad request response
func (o *EnrollOttCaBadRequest) WithWWWAuthenticate(wWWAuthenticate []string) *EnrollOttCaBadRequest {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the enroll ott ca bad request response
func (o *EnrollOttCaBadRequest) SetWWWAuthenticate(wWWAuthenticate []string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the enroll ott ca bad request response
func (o *EnrollOttCaBadRequest) WithPayload(payload *rest_model.APIErrorEnvelope) *EnrollOttCaBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the enroll ott ca bad request response
func (o *EnrollOttCaBadRequest) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *EnrollOttCaBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	var wWWAuthenticateIR []string
	for _, wWWAuthenticateI := range o.WWWAuthenticate {
		wWWAuthenticateIS := wWWAuthenticateI
		if wWWAuthenticateIS != "" {
			wWWAuthenticateIR = append(wWWAuthenticateIR, wWWAuthenticateIS)
		}
	}
	wWWAuthenticate := swag.JoinByFormat(wWWAuthenticateIR, "")
	if len(wWWAuthenticate) > 0 {
		hv := wWWAuthenticate[0]
		if hv != "" {
			rw.Header().Set("WWW-Authenticate", hv)
		}
	}

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// EnrollOttCaTooManyRequestsCode is the HTTP code returned for type EnrollOttCaTooManyRequests
const EnrollOttCaTooManyRequestsCode int = 429

/*
EnrollOttCaTooManyRequests The resource requested is rate limited and the rate limit has been exceeded

swagger:response enrollOttCaTooManyRequests
*/
type EnrollOttCaTooManyRequests struct {
	/*Denotes different type of security token related information

	 */
	WWWAuthenticate []string `json:"WWW-Authenticate"`

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewEnrollOttCaTooManyRequests creates EnrollOttCaTooManyRequests with default headers values
func NewEnrollOttCaTooManyRequests() *EnrollOttCaTooManyRequests {

	return &EnrollOttCaTooManyRequests{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the enroll ott ca too many requests response
func (o *EnrollOttCaTooManyRequests) WithWWWAuthenticate(wWWAuthenticate []string) *EnrollOttCaTooManyRequests {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the enroll ott ca too many requests response
func (o *EnrollOttCaTooManyRequests) SetWWWAuthenticate(wWWAuthenticate []string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the enroll ott ca too many requests response
func (o *EnrollOttCaTooManyRequests) WithPayload(payload *rest_model.APIErrorEnvelope) *EnrollOttCaTooManyRequests {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the enroll ott ca too many requests response
func (o *EnrollOttCaTooManyRequests) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *EnrollOttCaTooManyRequests) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	var wWWAuthenticateIR []string
	for _, wWWAuthenticateI := range o.WWWAuthenticate {
		wWWAuthenticateIS := wWWAuthenticateI
		if wWWAuthenticateIS != "" {
			wWWAuthenticateIR = append(wWWAuthenticateIR, wWWAuthenticateIS)
		}
	}
	wWWAuthenticate := swag.JoinByFormat(wWWAuthenticateIR, "")
	if len(wWWAuthenticate) > 0 {
		hv := wWWAuthenticate[0]
		if hv != "" {
			rw.Header().Set("WWW-Authenticate", hv)
		}
	}

	rw.WriteHeader(429)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// EnrollOttCaServiceUnavailableCode is the HTTP code returned for type EnrollOttCaServiceUnavailable
const EnrollOttCaServiceUnavailableCode int = 503

/*
EnrollOttCaServiceUnavailable The request could not be completed due to the server being busy or in a temporarily bad state

swagger:response enrollOttCaServiceUnavailable
*/
type EnrollOttCaServiceUnavailable struct {
	/*Denotes different type of security token related information

	 */
	WWWAuthenticate []string `json:"WWW-Authenticate"`

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewEnrollOttCaServiceUnavailable creates EnrollOttCaServiceUnavailable with default headers values
func NewEnrollOttCaServiceUnavailable() *EnrollOttCaServiceUnavailable {

	return &EnrollOttCaServiceUnavailable{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the enroll ott ca service unavailable response
func (o *EnrollOttCaServiceUnavailable) WithWWWAuthenticate(wWWAuthenticate []string) *EnrollOttCaServiceUnavailable {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the enroll ott ca service unavailable response
func (o *EnrollOttCaServiceUnavailable) SetWWWAuthenticate(wWWAuthenticate []string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the enroll ott ca service unavailable response
func (o *EnrollOttCaServiceUnavailable) WithPayload(payload *rest_model.APIErrorEnvelope) *EnrollOttCaServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the enroll ott ca service unavailable response
func (o *EnrollOttCaServiceUnavailable) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *EnrollOttCaServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	var wWWAuthenticateIR []string
	for _, wWWAuthenticateI := range o.WWWAuthenticate {
		wWWAuthenticateIS := wWWAuthenticateI
		if wWWAuthenticateIS != "" {
			wWWAuthenticateIR = append(wWWAuthenticateIR, wWWAuthenticateIS)
		}
	}
	wWWAuthenticate := swag.JoinByFormat(wWWAuthenticateIR, "")
	if len(wWWAuthenticate) > 0 {
		hv := wWWAuthenticate[0]
		if hv != "" {
			rw.Header().Set("WWW-Authenticate", hv)
		}
	}

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
