// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package enrollment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/openziti/edge-api/rest_model"
)

// ListEnrollmentsReader is a Reader for the ListEnrollments structure.
type ListEnrollmentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListEnrollmentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListEnrollmentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListEnrollmentsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewListEnrollmentsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewListEnrollmentsTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /enrollments] listEnrollments", response, response.Code())
	}
}

// NewListEnrollmentsOK creates a ListEnrollmentsOK with default headers values
func NewListEnrollmentsOK() *ListEnrollmentsOK {
	return &ListEnrollmentsOK{}
}

/*
ListEnrollmentsOK describes a response with status code 200, with default header values.

A list of enrollments
*/
type ListEnrollmentsOK struct {
	Payload *rest_model.ListEnrollmentsEnvelope
}

// IsSuccess returns true when this list enrollments o k response has a 2xx status code
func (o *ListEnrollmentsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list enrollments o k response has a 3xx status code
func (o *ListEnrollmentsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list enrollments o k response has a 4xx status code
func (o *ListEnrollmentsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list enrollments o k response has a 5xx status code
func (o *ListEnrollmentsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list enrollments o k response a status code equal to that given
func (o *ListEnrollmentsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list enrollments o k response
func (o *ListEnrollmentsOK) Code() int {
	return 200
}

func (o *ListEnrollmentsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /enrollments][%d] listEnrollmentsOK %s", 200, payload)
}

func (o *ListEnrollmentsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /enrollments][%d] listEnrollmentsOK %s", 200, payload)
}

func (o *ListEnrollmentsOK) GetPayload() *rest_model.ListEnrollmentsEnvelope {
	return o.Payload
}

func (o *ListEnrollmentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rest_model.ListEnrollmentsEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListEnrollmentsBadRequest creates a ListEnrollmentsBadRequest with default headers values
func NewListEnrollmentsBadRequest() *ListEnrollmentsBadRequest {
	return &ListEnrollmentsBadRequest{}
}

/*
ListEnrollmentsBadRequest describes a response with status code 400, with default header values.

The supplied request contains invalid fields or could not be parsed (json and non-json bodies). The error's code, message, and cause fields can be inspected for further information
*/
type ListEnrollmentsBadRequest struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this list enrollments bad request response has a 2xx status code
func (o *ListEnrollmentsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list enrollments bad request response has a 3xx status code
func (o *ListEnrollmentsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list enrollments bad request response has a 4xx status code
func (o *ListEnrollmentsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this list enrollments bad request response has a 5xx status code
func (o *ListEnrollmentsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this list enrollments bad request response a status code equal to that given
func (o *ListEnrollmentsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the list enrollments bad request response
func (o *ListEnrollmentsBadRequest) Code() int {
	return 400
}

func (o *ListEnrollmentsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /enrollments][%d] listEnrollmentsBadRequest %s", 400, payload)
}

func (o *ListEnrollmentsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /enrollments][%d] listEnrollmentsBadRequest %s", 400, payload)
}

func (o *ListEnrollmentsBadRequest) GetPayload() *rest_model.APIErrorEnvelope {
	return o.Payload
}

func (o *ListEnrollmentsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListEnrollmentsUnauthorized creates a ListEnrollmentsUnauthorized with default headers values
func NewListEnrollmentsUnauthorized() *ListEnrollmentsUnauthorized {
	return &ListEnrollmentsUnauthorized{}
}

/*
ListEnrollmentsUnauthorized describes a response with status code 401, with default header values.

The supplied session does not have the correct access rights to request this resource
*/
type ListEnrollmentsUnauthorized struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this list enrollments unauthorized response has a 2xx status code
func (o *ListEnrollmentsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list enrollments unauthorized response has a 3xx status code
func (o *ListEnrollmentsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list enrollments unauthorized response has a 4xx status code
func (o *ListEnrollmentsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this list enrollments unauthorized response has a 5xx status code
func (o *ListEnrollmentsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this list enrollments unauthorized response a status code equal to that given
func (o *ListEnrollmentsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the list enrollments unauthorized response
func (o *ListEnrollmentsUnauthorized) Code() int {
	return 401
}

func (o *ListEnrollmentsUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /enrollments][%d] listEnrollmentsUnauthorized %s", 401, payload)
}

func (o *ListEnrollmentsUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /enrollments][%d] listEnrollmentsUnauthorized %s", 401, payload)
}

func (o *ListEnrollmentsUnauthorized) GetPayload() *rest_model.APIErrorEnvelope {
	return o.Payload
}

func (o *ListEnrollmentsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListEnrollmentsTooManyRequests creates a ListEnrollmentsTooManyRequests with default headers values
func NewListEnrollmentsTooManyRequests() *ListEnrollmentsTooManyRequests {
	return &ListEnrollmentsTooManyRequests{}
}

/*
ListEnrollmentsTooManyRequests describes a response with status code 429, with default header values.

The resource requested is rate limited and the rate limit has been exceeded
*/
type ListEnrollmentsTooManyRequests struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this list enrollments too many requests response has a 2xx status code
func (o *ListEnrollmentsTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list enrollments too many requests response has a 3xx status code
func (o *ListEnrollmentsTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list enrollments too many requests response has a 4xx status code
func (o *ListEnrollmentsTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this list enrollments too many requests response has a 5xx status code
func (o *ListEnrollmentsTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this list enrollments too many requests response a status code equal to that given
func (o *ListEnrollmentsTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the list enrollments too many requests response
func (o *ListEnrollmentsTooManyRequests) Code() int {
	return 429
}

func (o *ListEnrollmentsTooManyRequests) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /enrollments][%d] listEnrollmentsTooManyRequests %s", 429, payload)
}

func (o *ListEnrollmentsTooManyRequests) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /enrollments][%d] listEnrollmentsTooManyRequests %s", 429, payload)
}

func (o *ListEnrollmentsTooManyRequests) GetPayload() *rest_model.APIErrorEnvelope {
	return o.Payload
}

func (o *ListEnrollmentsTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
